name: "Preevy Down"
description: "Runs the Preevy `down` command"
author: "Livecycle"
branding:
  icon: box
  color: blue
inputs:
  profile-url:
    required: true
    description: "The Preevy profile URL"
  args:
    required: false
    description: "Additional args to provide to the `down` command."
  docker-compose-yaml-paths:
    required: false
    description: "Array of comma separated paths to docker compose files. Uses current working directory if not provided."
  version:
    required: false
    description: "Version of Preevy to use. Defaults to latest."
    default: latest
  node-cache:
    required: false
    description: "Specify Node package manager for caching. Supported values: npm, yarn, pnpm, or ''. See https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data"
    default: npm
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: ${{ inputs.node-cache }}

    - name: Run Preevy down
      shell: bash
      id: run_preevy_down
      run: |
        file_opt=""
        if [[ ! -z "${{ inputs.docker-compose-yaml-paths }}" ]]; then
          file_opt="-f ${{ inputs.docker-compose-yaml-paths }}"
        fi

        npx -- preevy down --profile '${{ inputs.profile-url }}' ${file_opt} ${{ inputs.args }}
